### ISSUE TITLE
more fast http request parse.

### ISSUE THREAD

**Issue by 2vg** [2vg/mofuw#20]
maybe, implements SIMD proc in mofuparser.

**Comment by sclee15** [comment]
SIMD looks nice for a header parser

**Comment by 2vg** [comment]
awesome SIMD library of Nim
[nim_simd](https://github.com/jackmott/nim_simd)

**Comment by kubo39** [comment]
Unfortunately, it looks tha nim_simd library doesn't support PCMPxSTRx family.
So I'll recommend to wtite another simd library, these articles would help you :)

* [PCMPxSTRx 命令の使い方 (Japanese)](http://www.nminoru.jp/~nminoru/programming/pcmpxstrx.html)
* [HTTPパーサにおけるSSE4.2最適化の威力と注意点 (Japanese)](http://blog.cybozu.io/entry/7982)

**Comment by 2vg** [comment]
@kubo39 thx!!! Well, I'll make a new library.
However, because this parser is fast enough, I do not intend to make it now.

**Comment by 2vg** [comment]
[https://github.com/bsegovia/x86_simd.nim](https://github.com/bsegovia/x86_simd.nim]

**Comment by kubo39** [comment]
Still missing PCMPxSTRx family, isn't it?

**Comment by 2vg** [comment]
SSE 4.2 is included, but I do not know if it can be used.

**Comment by 2vg** [comment]
PCMPxSTRx seems to be included

**Comment by 2vg** [comment]
Rust's httparse,
I do not seem to be using SSE 4.2 functions.[https://github.com/seanmonstar/httparse/blob/master/src/simd/sse42.rs](https://github.com/seanmonstar/httparse/blob/master/src/simd/sse42.rs)

**Comment by kubo39** [comment]
Wow, that's interesting. httparse shows vectorized-compare based matching for header values is faster than picohttpparser AVX2/SSE4.2.

**Comment by 2vg** [comment]
Implementation is complete, then close Issue.
It seems that it got about 1.5 times faster.
[https://github.com/2vg/mofuparser/commit/a48625cb0fc77c47631b69b5651aca172686465f](https://github.com/2vg/mofuparser/commit/a48625cb0fc77c47631b69b5651aca172686465f)
