### ISSUE TITLE
Memory grows with each request

### ISSUE THREAD

**Issue by tim-st** [2vg/mofuw#31]
Thanks for your work on this!
When I tried your minimal example
```nim
import mofuw

proc handler(req: mofuwReq, res: mofuwRes) {.async.} =
  routes:
    get "/":
      mofuwResp(
        HTTP200,
        "text/plain",
        "Hello, World!"
      )

handler.mofuwRun() # default listening port: 8080
```
in release mode and debug mode on windows 10 and
Nim Compiler Version 0.18.0 [Windows: amd64]
I recognize that the memory grows with each call to `http://127.0.0.1:8080/` (~80kb per 10 times pressing F5 in browser) and then stays at this size until I do next call. I have the feeling, when I do enough calls, the memory is filled completely.
Am I doing something wrong? Should I manually free the memory?

**Comment by tim-st** [comment]
Update: The memory went down to 1.6mb again, maybe this was due to open connections or a time related setting.

**Comment by tim-st** [comment]
Could be related to this one (windows only):
https://github.com/nim-lang/Nim/issues/5589

**Comment by 2vg** [comment]
This problem may be a problem with Nim, but you need to have Issue open until you solve it

**Comment by tim-st** [comment]
I now tested it using `wrk` and it seems to work good for a high amount of connections (similiar to jester), so it was no problem. Sorry for the trouble.
