### ISSUE TITLE
type mismatch: got <port: int literal(8080), handler: proc (ctx: MofuwCtx): Future[system.void]{.locks: <unknown>.}>

### ISSUE THREAD

**Issue by 15174400** [2vg/mofuw#59]
app.nim

import mofuw
import strutils
import tables

proc mytest*(x:string):string=
    result="hello " & x

type
    appHandler* =ref object of RootObj
        proctable* :Table[string,proc(x:string):string]

proc initProcTable* (this:appHandler):void {.inline.}=
    this.proctable["mytest"]=mytest

proc call* (this:appHandler,ctx:MofuwCtx):void {.inline.}=
    var webresult:string=this.proctable [ctx.body] ("world")
    mofuwResp(HTTP200,"text/plain",webresult)

myServer.nim

import mofuw
import strutils
import app
let myapp=appHandler()
myapp.initProcTable()
routes:
    post "/test":
        myapp.call(ctx)

newServeCtx(
    port=8080,
    handler=mofuwHandler)
.serve()

compile error:  type mismatch: got <port: int literal(8080), handler: proc (ctx: MofuwCtx): Future[system.void]{.locks: <unknown>.}>
but expected one of: 
proc newServeCtx(servername = "mofuw"; port: int;
                handler, hookrequest, hookresponse: MofuwHandler = nil;
                readBufferSize, writeBufferSize = 4096; maxBodySize = 1048576 * 5;
                timeout = 3 * 1000; poolsize = 128; isSSL = false): ServeCtx

expression: newServeCtx(port = 8080, handler = mofuwHandler)

**Comment by 15174400** [comment]
type mismatch: got <port: int literal(8080), handler: proc (ctx: MofuwCtx): Future[system.void]{.locks: <unknown>.}>
but expected one of: 
proc newServeCtx(servername = "mofuw"; port: int;
                handler, hookrequest, hookresponse: MofuwHandler = nil;
                readBufferSize, writeBufferSize = 4096; maxBodySize = 1048576 * 5;
                timeout = 3 * 1000; poolsize = 128; isSSL = false): ServeCtx

expression: newServeCtx(port = 8080, handler = mofuwHandler)

**Comment by 2vg** [comment]
I found the cause, so I will show a solution.
Since the server is built for each thread, accessing global variables is a problem.
Compiling is passed by using {.threadvar.}.

```
import mofuw
import strutils, tables

proc mytest*(x:string):string=
  result="hello " & x
  
type
  appHandler* =ref object of RootObj
    proctable* :Table[string,proc(x:string):string]
  
proc initProcTable* (this:appHandler):void {.inline.}=
  this.proctable["mytest"]=mytest
  
proc call* (this:appHandler,ctx:MofuwCtx):void {.inline.}=
  var webresult:string=this.proctable[ctx.body]("world")
  mofuwResp(HTTP200,"text/plain",webresult)

var myapp {.threadvar.}: appHandler

myapp = appHandler()
myapp.initProcTable()

routes:
  post "/test":
    myapp.call(ctx)

newServeCtx(
  port = 8080,
  handler = mofuwHandler
).serve()
```
