### ISSUE TITLE
`mofuw` creates wrong error message when accessing shared memory

### ISSUE THREAD

**Issue by tim-st** [2vg/mofuw#62]
```nim
  import mofuw

  var s = ""

  proc handler(ctx: MofuwCtx) {.async.} =
    let t = s

  newServeCtx(
    port = 8080,
    handler = handler
  ).serve()
```

creates a type mismatch error, normally I would expect that this compiles with only a warning.
Tested using Nim Compiler Version 0.18.1 [Windows: amd64]; Compiled at 2018-08-26.

**Comment by 2vg** [comment]
using `threadvar`.

**Comment by tim-st** [comment]
Thanks for the  answer, I just saw that the problem came from `asynchttpserver` not with `mofuw`.
